# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

InterviewQuestion.create(question: "What are your strengths?")
InterviewQuestion.create(question: "What are your weaknesses?")
InterviewQuestion.create(question: "Why are you interested in working for this company?")
InterviewQuestion.create(question: "Where do you see yourself in five years?")
InterviewQuestion.create(question: "Where do you see yourself in ten years?")
InterviewQuestion.create(question: "Why do you want to leave your current company?")
InterviewQuestion.create(question: "What can you offer us that someone else can not?")
InterviewQuestion.create(question: "Are you willing to relocate?")
InterviewQuestion.create(question: "Are you willing to travel?")
InterviewQuestion.create(question: "Tell me about an accomplishment you are most proud of.")
InterviewQuestion.create(question: "Tell me about a time you made a mistake.")
InterviewQuestion.create(question: "What is your dream job?")
InterviewQuestion.create(question: "Discuss your resume.")
InterviewQuestion.create(question: "Discuss your educational background.")
InterviewQuestion.create(question: "Describe yourself.")
InterviewQuestion.create(question: "Tell me how you handled a difficult situation.")
InterviewQuestion.create(question: "Why should we hire you?")
InterviewQuestion.create(question: "Why are you looking for a new job?")
InterviewQuestion.create(question: "Would you work holidays/weekends?")
InterviewQuestion.create(question: "How would you deal with an angry or irate customer?")
InterviewQuestion.create(question: "What are your salary requirements?")
InterviewQuestion.create(question: "Give a time when you went above and beyond the requirements for a project.")
InterviewQuestion.create(question: "What was your biggest failure?")
InterviewQuestion.create(question: "What motivates you?")
InterviewQuestion.create(question: "What’s your availability?")
InterviewQuestion.create(question: "Who’s your mentor?")
InterviewQuestion.create(question: "Tell me about a time when you disagreed with your boss.")
InterviewQuestion.create(question: "How do you handle pressure?")
InterviewQuestion.create(question: "What are your career goals?")
InterviewQuestion.create(question: "What gets you up in the morning?")
InterviewQuestion.create(question: "If I called your boss right now and asked him/her what is an area that you could improve on, what would he/she say?")
InterviewQuestion.create(question: "Are you a leader or a follower?")
InterviewQuestion.create(question: "What was the last book you’ve read for fun?")
InterviewQuestion.create(question: "What are your co-worker pet peeves?")
InterviewQuestion.create(question: "What are your hobbies?")
InterviewQuestion.create(question: "What is your favorite website?")
InterviewQuestion.create(question: "What makes you uncomfortable?")
InterviewQuestion.create(question: "What are some of your leadership experiences?")
InterviewQuestion.create(question: "How would you fire someone?")
InterviewQuestion.create(question: "What do you like the most and least about working in this industry?")
InterviewQuestion.create(question: "Would you work 40+ hours a week?")
InterviewQuestion.create(question: "What questions haven’t I asked you?")
InterviewQuestion.create(question: "What questions do you have for me?")
InterviewQuestion.create(question: "Tell me about yourself.")
InterviewQuestion.create(question: "What's your ideal company?")
InterviewQuestion.create(question: "Why should we hire you?")
InterviewQuestion.create(question: "What did you like least about your last job?")
InterviewQuestion.create(question: "When were you most satisfied in your job?")
InterviewQuestion.create(question: "What were the responsibilities of your last position?")
InterviewQuestion.create(question: "Do you have any questions for me?")
InterviewQuestion.create(question: "What was the last project you led, and what was its outcome?")
InterviewQuestion.create(question: "Can you describe a time when your work was criticized?")
InterviewQuestion.create(question: "Have you ever been on a team where someone was not pulling their own weight? How did you handle it?")
InterviewQuestion.create(question: "Tell me about a time when you had to give someone difficult feedback. How did you handle it?")
InterviewQuestion.create(question: "What is your greatest failure, and what did you learn from it?")
InterviewQuestion.create(question: "How do you handle working with people who annoy you?")
InterviewQuestion.create(question: "If I were your supervisor and asked you to do something that you disagreed with, what would you do?")
InterviewQuestion.create(question: "What was the most difficult period in your life, and how did you deal with it?")
InterviewQuestion.create(question: "If you found out your company was doing something against the law, like fraud, what would you do?")
InterviewQuestion.create(question: "What assignment was too difficult for you, and how did you resolve the issue?")
InterviewQuestion.create(question: "Describe how you would handle a situation if you were required to finish multiple tasks by the end of the day, and there was no way that you could finish them.")
InterviewQuestion.create(question: "What salary are you seeking?")
InterviewQuestion.create(question: "What's your salary history?")
InterviewQuestion.create(question: "How do you want to improve yourself in the next year?")
InterviewQuestion.create(question: "If I were to ask your last supervisor to provide you additional training or exposure, what would she suggest?")
InterviewQuestion.create(question: "How would you describe your work style?")
InterviewQuestion.create(question: "What would be your ideal working environment?")
InterviewQuestion.create(question: "What do you look for in terms of culture—structured or entrepreneurial?")
InterviewQuestion.create(question: "What techniques and tools do you use to keep yourself organized?")
InterviewQuestion.create(question: "If you had to choose one, would you consider yourself a big-picture person or a detail-oriented person?")
InterviewQuestion.create(question: "Who was your favorite manager and why?")
InterviewQuestion.create(question: "What do you think of your previous boss?")
InterviewQuestion.create(question: "Was there a person in your career who really made a difference?")
InterviewQuestion.create(question: "What kind of personality do you work best with and why?")
InterviewQuestion.create(question: "What are your lifelong dreams?")
InterviewQuestion.create(question: "What are three positive things your last boss would say about you?")
InterviewQuestion.create(question: "What three character traits would your friends use to describe you?")
InterviewQuestion.create(question: "What is your greatest fear?")
InterviewQuestion.create(question: "What's the most important thing you learned in school?")
InterviewQuestion.create(question: "Why did you choose your major?")
InterviewQuestion.create(question: "What is your greatest achievement outside of work?")
InterviewQuestion.create(question: "What are the qualities of a good leader?")
InterviewQuestion.create(question: "What are the qualities of a bad leader?")
InterviewQuestion.create(question: "Do you think a leader should be feared or liked?")
InterviewQuestion.create(question: "How would you feel about working for someone who knows less than you?")
InterviewQuestion.create(question: "There's no right or wrong answer, but if you could be anywhere in the world right now, where would you be?")
InterviewQuestion.create(question: "What would you do if you won the lottery?")
InterviewQuestion.create(question: "Who are your heroes?")
InterviewQuestion.create(question: "What do you like to do for fun?")
InterviewQuestion.create(question: "What do you do in your spare time?")
InterviewQuestion.create(question: "If you could choose one superhero power, what would it be and why?")
InterviewQuestion.create(question: "How do you handle stress and pressure?")






